"""phase 1 media intake

Revision ID: 1efb4fe85a38
Revises: 047de1e60a22
Create Date: 2026-09-21 13:59:46.035101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1efb4fe85a38'
down_revision: Union[str, Sequence[str], None] = '047de1e60a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='ingested', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_case_id'), 'media_assets', ['case_id'], unique=False)
    op.create_index(op.f('ix_media_assets_sha256'), 'media_assets', ['sha256'], unique=False)
    op.create_table('media_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_versions_media_asset_id'), 'media_versions', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_media_versions_sha256'), 'media_versions', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_versions_sha256'), table_name='media_versions')
    op.drop_index(op.f('ix_media_versions_media_asset_id'), table_name='media_versions')
    op.drop_table('media_versions')
    op.drop_index(op.f('ix_media_assets_sha256'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_case_id'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
