"""add media metadata

Revision ID: 9f9e88c8892d
Revises: 1efb4fe85a38
Create Date: 2026-09-25 21:53:48.521732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f9e88c8892d'
down_revision: Union[str, Sequence[str], None] = '1efb4fe85a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('duration_seconds', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('frame_rate', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('video_codec', sa.String(length=128), nullable=True),
    sa.Column('audio_codec', sa.String(length=128), nullable=True),
    sa.Column('audio_sample_rate', sa.Integer(), nullable=True),
    sa.Column('audio_channels', sa.Integer(), nullable=True),
    sa.Column('probe_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_metadata_media_asset_id'), 'media_metadata', ['media_asset_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_metadata_media_asset_id'), table_name='media_metadata')
    op.drop_table('media_metadata')
    # ### end Alembic commands ###
